version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.20 # Image Node officielle CircleCI
    working_directory: ~/project

jobs:
  build:
    executor: node-executor
    steps:
      - checkout # Récupérer le code
      - run: npm ci # Installer les dépendances de manière propre (package-lock.json)
      - run:
          name: Lancer les tests
          command: npm run test # Exécuter les tests (Vitest ou Jest selon config)
      - run:
          name: Build du projet
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist # Sauvegarder le dossier build pour le job deploy

  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Déploiement vers Render
          command: |
            curl -X POST "https://api.render.com/deploy/srv-d0q973adbo4c73brvaj0?key=Zkym-WbE_A4"

workflows:
  deploy-on-push:
    jobs:
      - build
      - deploy:
          requires:
            - build
